.c9/metadata/workspace/adumor/urls.py
{"filter":false,"title":"urls.py","tooltip":"/adumor/urls.py","undoManager":{"mark":0,"position":0,"stack":[[{"start":{"row":11,"column":0},"end":{"row":12,"column":0},"action":"remove","lines":["    url(r'registro_usuario/', views.registro),",""],"id":1}]]},"ace":{"folds":[],"scrolltop":0,"scrollleft":0,"selection":{"start":{"row":9,"column":37},"end":{"row":9,"column":37},"isBackwards":false},"options":{"guessTabSize":true,"useWrapMode":false,"wrapToView":true},"firstLineState":0},"timestamp":1539710200059,"hash":"42288b8148ae49e6d140a94538dafb73ab94c5de"}

adumor/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .import views
from usuarios.views import login_view
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^usuarios/', include('usuarios.urls', namespace='usuarios')),
    url(r'^anuncios/', include('anuncios.urls', namespace='anuncios')),
    url(r'^direccion/', include('direcciones.urls', namespace='direcciones')),
    url(r'^about/$', views.about),
    url(r'^$', views.homepage),
]

urlpatterns += staticfiles_urlpatterns()

anuncios/urls.py
from django.conf.urls import url
from .views import crear_anuncio, AnuncioList, AnuncioDelete, AnuncioEdit, AnuncioPostulanteList, DetailAnuncio, postular


namespace = 'anuncios'

urlpatterns = [
    url(r'^$', crear_anuncio, name="crear_anuncio"),
    url(r'^display_anuncio/(?P<pk>\d+)/$', DetailAnuncio.as_view(), name="display_anuncio"),
    url(r'^empresa_lista_anuncio/', AnuncioList.as_view(), name="empresa_lista_anuncio"),
    url(r'^postulante_lista_anuncio/', AnuncioPostulanteList.as_view(), name="postulante_lista_anuncio"),
    url(r'^editar/(?P<pk>\d+)/$', AnuncioEdit.as_view(), name='anuncio_editar'),
    url(r'^eliminar/(?P<pk>\d+)/$', AnuncioDelete.as_view(), name='anuncio_eliminar'),
    url(r'^postular/(?P<pk>\d+)/$', postular, name='postular'),
]

.c9/metadata/workspace/anuncios/models.py
{"filter":false,"title":"models.py","tooltip":"/anuncios/models.py","undoManager":{"mark":-1,"position":-1,"stack":[]},"ace":{"folds":[],"scrolltop":0,"scrollleft":0,"selection":{"start":{"row":16,"column":42},"end":{"row":16,"column":42},"isBackwards":false},"options":{"guessTabSize":true,"useWrapMode":false,"wrapToView":true},"firstLineState":0},"timestamp":1540219344083,"hash":"623cd13df9be1b6239d0eeed83cd3894b68c01e3"}

anuncios/models.py
from __future__ import unicode_literals

from django.db import models
from adumor.models import Idioma
from usuarios.models import Usuarios, Postulante
from direcciones.models import Direccion

# Create your models here.


class Anuncio(models.Model):
    id_anuncio = models.IntegerField(primary_key=True)
    titulo_anuncio = models.CharField(max_length=250)
    alter_titulo_anuncio = models.CharField(max_length=250, blank=True, null=True)
    detalle_anuncio = models.CharField(max_length=600)
    alter_detalle_anuncio = models.CharField(max_length=600, blank=True, null=True)
    fecha_anuncio = models.DateTimeField()
    fecha_cierre_anuncio = models.DateTimeField(blank=True, null=True)
    estado_anuncio = models.IntegerField()
    tipo_trabajo = models.CharField(max_length=45, blank=True, null=True)
    salario = models.IntegerField(blank=True, null=True)
    user_ptr_id = models.ForeignKey('usuarios.Empresa', models.DO_NOTHING, db_column='user_ptr_id')
    id_idioma_alter = models.ForeignKey('adumor.Idioma', models.DO_NOTHING, db_column='id_idioma_alter', blank=True, null=True)
    id_direccion = models.ForeignKey(Direccion, models.DO_NOTHING, db_column='id_direccion', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'anuncio'

class EstadoPostulacion(models.Model):
    id_estado_postulacion = models.AutoField(primary_key=True)
    desc_estado_postulacion = models.CharField(max_length=45)

    def __str__(self):
        return (self.desc_estado_postulacion)

    class Meta:
        managed = False
        db_table = 'estado_postulacion'

class Postulacion(models.Model):
    id_postulacion = models.AutoField(primary_key=True)
    fecha_postulacion = models.DateTimeField()
    id_usuario_postulante = models.ForeignKey('usuarios.Postulante', models.DO_NOTHING, db_column='id_usuario_postulante')
    id_anuncio = models.ForeignKey(Anuncio, models.DO_NOTHING, db_column='id_anuncio')
    id_estado_postulacion = models.ForeignKey(EstadoPostulacion, models.DO_NOTHING, db_column='id_estado_postulacion')
    fecha_cambio_postulacion = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'postulacion'
        
class TipoAnuncio(models.Model):
    id_tipo_anuncio = models.IntegerField(primary_key=True)
    desc_tipo_anuncio = models.CharField(max_length=45)
    
    def __str__(self):
        return (self.desc_tipo_anuncio)

    class Meta:
        managed = False
        db_table = 'tipo_anuncio'

.c9/metadata/workspace/anuncios/forms.py
{"filter":false,"title":"forms.py","tooltip":"/anuncios/forms.py","undoManager":{"mark":-1,"position":-1,"stack":[]},"ace":{"folds":[],"scrolltop":370.859375,"scrollleft":0,"selection":{"start":{"row":35,"column":0},"end":{"row":45,"column":9},"isBackwards":false},"options":{"guessTabSize":true,"useWrapMode":false,"wrapToView":true},"firstLineState":{"row":24,"state":"start","mode":"ace/mode/python"}},"timestamp":1540218834894,"hash":"277304ed222517dd2ab214b02033ca87c0c03d6e"}

anuncios/forms.py
from django import forms
from . import models

TIPO_TRABAJO= (
( 'Indefinido', 'Indefinido'),
('Plazo Fijo', 'Plazo Fijo'),
('Parcial', 'Parcial'),
)

class CrearAnuncio(forms.ModelForm):
    class Meta:
        model = models.Anuncio
        fields = [ 
            'titulo_anuncio', 
            'alter_titulo_anuncio', 
            'detalle_anuncio', 
            'alter_detalle_anuncio', 
            'fecha_cierre_anuncio',
            'tipo_trabajo',
            'salario',
            'id_direccion',
            'id_idioma_alter',
            ]
        widgets = {
            'titulo_anuncio': forms.TextInput(attrs={'class':'with-border'}), 
            'alter_titulo_anuncio': forms.TextInput(attrs={'class':'with-border'}), 
            'detalle_anuncio': forms.Textarea(attrs={'class':'with-border', 'cols':'10', 'rows':'1'}), 
            'alter_detalle_anuncio': forms.Textarea(attrs={'class':'with-border', 'cols':'10', 'rows':'1'}), 
            'fecha_cierre_anuncio': forms.TextInput(attrs={'class':'form_datetime'}),
            'tipo_trabajo': forms.Select(choices=TIPO_TRABAJO),
            'salario': forms.TextInput(attrs={'class':'with-border'}),
            'id_direccion': forms.Select(attrs={'class':'with-border'}),
            'id_idioma_alter': forms.Select(attrs={'class':'with-border'}),
        }
        
class PostularForm(forms.ModelForm):
    class Meta:
        model = models.Postulacion
        exclude = [
        'id_postulacion',
        'fecha_postulacion',
        'id_usuario_postulante',
        'id_anuncio',
        'id_estado_postulacion',
        'fecha_cambio_postulacion',
        ]

anuncios/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.views.generic import ListView, UpdateView, DeleteView, DetailView, TemplateView
from django.core.urlresolvers import reverse_lazy
from .forms import CrearAnuncio, PostularForm
from .models import Anuncio, EstadoPostulacion
from usuarios.models import Empresa, Postulante
from direcciones.models import Direccion

# Create your views here.

def postular(request, pk):
    if request.method == 'POST':
        form = PostularForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.fecha_postulacion = timezone.now()
            instance.id_usuario_postulante = Postulante.objects.get(pk=int(request.user.pk))
            instance.id_anuncio = Anuncio.objects.get(pk=pk)
            instance.id_estado_postulacion = EstadoPostulacion.objects.get(pk=1)
            instance.fecha_cambio_postulacion = timezone.now()
            instance.save()
            return redirect('anuncios:postulante_lista_anuncio') 
    else:
        form = PostularForm()
    return render(request, 'anuncios/postulante_lista_anuncio.html', {'form': form})
        

def crear_anuncio(request):
    if request.method == 'POST':
        form = CrearAnuncio(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            anuncio_final = Anuncio.objects.last()
            instance.id_anuncio = anuncio_final.id_anuncio + 1
            instance.fecha_anuncio = timezone.now()
            instance.fecha_cierre_anuncio = timezone.now()
            instance.user_ptr_id = Empresa.objects.get(pk=request.user.pk)
            instance.estado_anuncio = 1;
            instance.save()
            return redirect('anuncios:empresa_lista_anuncio')                
    else:
        form = CrearAnuncio()
    return render(request, 'anuncios/empresa_anuncio.html', {'form': form})
    
class AnuncioList(ListView):
    model = Anuncio
    template_name = 'anuncios/empresa_lista_anuncio.html'
    
class AnuncioPostulanteList(ListView):
    model = Anuncio
    template_name = 'anuncios/postulante_lista_anuncio.html'
    
class AnuncioEdit(UpdateView):
    model = Anuncio
    form_class = CrearAnuncio
    template_name = 'anuncios/empresa_anuncio.html'
    success_url = reverse_lazy('anuncios:empresa_lista_anuncio')
    
class AnuncioDelete(DeleteView):
    model = Anuncio
    template_name = '/anuncios/anuncio_eliminar.html'
    success_url = reverse_lazy('anuncios:anuncio_eliminar')
    
class DetailAnuncio(DetailView):
    model = Anuncio
    template_name = 'anuncios/pagina_anuncio.html'
    success_url = reverse_lazy('anuncios:pagina_anuncio')
    

anuncios/templates/anuncios/anuncio_eliminar.html
{% extends 'anuncios/base_anuncio.html' %}
{% load staticfiles %}


{% block content %}


	<!-- Dashboard Content
	================================================== -->
	<div class="dashboard-content-container" data-simplebar>
		<div class="dashboard-content-inner" >
			
			<!-- Dashboard Headline -->
			<div class="dashboard-headline">
				<h3>Anuncio de Empleo</h3>

				<!-- Breadcrumbs -->
				<nav id="breadcrumbs" class="dark">
					<ul>
						<li><a href="#">Inicio</a></li>
						<li><a href="#">Panel</a></li>
						<li>Anuncio de Empleo</li>
					</ul>
				</nav>
			</div>
	
			<!-- Row -->
			<div class="row">

				<!-- Dashboard Box -->
				<div class="col-xl-12">
					<div class="dashboard-box margin-top-0">
						
						<!-- Headline -->
						<div class="headline">
							<h3><i class="icon-feather-folder-minus"></i>Eliminar Registro</h3>
						</div>
						<div class="content">
                        	<form method="post">
                            {% csrf_token %}
                            <div class="content with-padding padding-bottom-10">
							<div class="row">
                            <div class="col-xl-12">
                                <h4>¿ Desea Eliminar anuncio <b>{{ object.titulo_anuncio }}</b> ?</h4>
                            </div>
	                            <div class="col-xl-3">
	                            <button type="submit" class="button green ripple-effect big margin-top-30" value="Submit">Eliminar</button>
	                            </div>
	                            <div class="col-xl-3">
	                            <a class="button ripple-effect red big margin-top-30" href="{% url 'anuncios:empresa_lista_anuncio' %}" >Cancelar</a>
	                            </div>
	                            </div>
	       		 	</div>
                       	 	</form>
                      	</div>
	       		 	</div>
	       		 </div>
	       	</div>
			<!-- Row / End -->

			<!-- Footer -->
			<div class="dashboard-footer-spacer"></div>
			<div class="small-footer margin-top-15">
				<div class="small-footer-copyrights">
					2018 <strong>Bolsa de empleo</strong>
				</div>
				<div class="clearfix"></div>
			</div>
			<!-- Footer / End -->

		</div>
	</div>
	<!-- Dashboard Content / End -->
	
{% endblock %}

anuncios/templates/anuncios/base_anuncio.html
{% load staticfiles %}

<!doctype html>
<html lang="en">
<head>

<!-- Basic Page Needs
================================================== -->
<title>Bolsa de Empleo</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

<!-- CSS
================================================== -->
<link rel="stylesheet" href="{% static "css/style.css" %}">
<link rel="stylesheet" href="{% static "css/colors/blue.css" %}">
<link rel="stylesheet" href="{% static "css/bootstrap-datetimepicker.css" %}">

</head>
<body class="gray">

<!-- Wrapper -->
<div id="wrapper">

<!-- Header Container
================================================== -->
<header id="header-container" class="fullwidth dashboard-header not-sticky">

	<!-- Header -->
	<div id="header">
		<div class="container">
			
			<!-- Left Side Content -->
			<div class="left-side">
				
				<!-- Logo -->
				<div id="logo">
					<a href="{{ get_empresa_url}}"><img src="{% static "images/logo.png" %}" alt=""></a>
				</div>

				<!-- Main Navigation -->
				<nav id="navigation">
					<ul id="responsive">

						<li><a href="#" class="current">Panel Empleador</a>

							
						</li>
					</ul>
				</nav>
				<div class="clearfix"></div>
				<!-- Main Navigation / End -->
				
			</div>
			<!-- Left Side Content / End -->


			<!-- Right Side Content / End -->
			<div class="right-side">


				<!-- User Menu -->
				<div class="header-widget">

					<!-- Messages -->
					<div class="header-notifications user-menu">
						<div class="header-notifications-trigger">
							<a href="#"><div class="user-avatar status-online"><img src="{% static "images/empleador-02_small.png" %}" alt=""></div></a>
						</div>

						<!-- Dropdown -->
						<div class="header-notifications-dropdown">

							<!-- User Status -->
							<div class="user-status">

								<!-- User Name / Avatar -->
								<div class="user-details">
									<div class="user-avatar status-online"><img src="{% static "images/empleador-02_small.png" %}" alt=""></div>
									<div class="user-name">
										{{ get_razon_social }} <span>Empresa</span>
									</div>
								</div>
								

						</div>
						
						<ul class="user-menu-small-nav">
							<li><a href="/usuarios/panel_empresa"><i class="icon-material-outline-dashboard"></i> Panel</a></li>
							<li><a href="/usuarios/configuracion_empresa"><i class="icon-material-outline-settings"></i> Configuración</a></li>
							<li><a href="/usuarios/logout"><i class="icon-material-outline-power-settings-new"></i> Cerrar</a></li>
						</ul>

						</div>
					</div>

				</div>
				<!-- User Menu / End -->

				<!-- Mobile Navigation Button -->
				<span class="mmenu-trigger">
					<button class="hamburger hamburger--collapse" type="button">
						<span class="hamburger-box">
							<span class="hamburger-inner"></span>
						</span>
					</button>
				</span>

			</div>
			<!-- Right Side Content / End -->

		</div>
	</div>
	<!-- Header / End -->

</header>
<div class="clearfix"></div>
<!-- Header Container / End -->


<!-- Dashboard Container -->
<div class="dashboard-container">

	<!-- Dashboard Sidebar
	================================================== -->
	<div class="dashboard-sidebar">
		<div class="dashboard-sidebar-inner" data-simplebar>
			<div class="dashboard-nav-container">

				<!-- Responsive Navigation Trigger -->
				<a href="#" class="dashboard-responsive-nav-trigger">
					<span class="hamburger hamburger--collapse" >
						<span class="hamburger-box">
							<span class="hamburger-inner"></span>
						</span>
					</span>
					<span class="trigger-title">Panel Empresa</span>
				</a>
				
				<!-- Navegacion-->
				<div class="dashboard-nav">
					<div class="dashboard-nav-inner">

						<ul data-submenu-title="Postulante">
							<li class="active"><a href="/usuarios/panel_empresa"><i class="icon-material-outline-dashboard"></i> Panel</a></li>
							<li><a href="{{ get_empresa_url }}"><i class="icon-material-outline-rate-review"></i> Ficha personal</a></li>
							<li><a href="/anuncios"><i class="icon-material-outline-business-center"></i> Publicar Anuncio</a></li>
							<li><a href="/anuncios/empresa_lista_anuncio"><i class="icon-line-awesome-list-alt"></i> Listado Anuncios</a></li>
						</ul>
						


						<ul data-submenu-title="Cuenta">
							<li><a href="/usuarios/configuracion_empresa"><i class="icon-material-outline-settings"></i> Configuración</a></li>
							<li><a href="/usuarios/logout"><i class="icon-material-outline-power-settings-new"></i> Cerrar</a></li>
						</ul>
						
					</div>
				</div>
				<!-- Navegacion / Fin -->

			</div>
		</div>
	</div>
	<!-- Dashboard Sidebar / End -->



    {% block content %}
        
    {% endblock %}



</div>
<!-- Dashboard Container / End -->

</div>
<!-- Wrapper / End -->


<!-- Scripts
================================================== -->
<script src="{% static "js/jquery-3.3.1.min.js" %}"></script>
<script src="{% static "js/jquery-migrate-3.0.0.min.js" %}"></script>
<script src="{% static "js/mmenu.min.js" %}"></script>
<script src="{% static "js/tippy.all.min.js" %}"></script>
<script src="{% static "js/simplebar.min.js" %}"></script>
<script src="{% static "js/bootstrap-slider.min.js" %}"></script>
<script src="{% static "js/bootstrap-select.min.js" %}"></script>
<script src="{% static "js/snackbar.js" %}"></script>
<script src="{% static "js/clipboard.min.js" %}"></script>
<script src="{% static "js/counterup.min.js" %}"></script>
<script src="{% static "js/magnific-popup.min.js" %}"></script>
<script src="{% static "js/slick.min.js" %}"></script>
<script src="{% static "js/custom.js" %}"></script>

<!-- Snackbar // documentation: https://www.polonel.com/snackbar/ -->
<script>
// Snackbar for user status switcher
$('#snackbar-user-status label').click(function() { 
	Snackbar.show({
		text: 'Your status has been changed!',
		pos: 'bottom-center',
		showAction: false,
		actionText: "Dismiss",
		duration: 3000,
		textColor: '#fff',
		backgroundColor: '#383838'
	}); 
}); 
</script>

<!-- Chart.js // documentation: http://www.chartjs.org/docs/latest/ -->
<script src="{% static "js/chart.min.js" %}"></script>
<script>
	Chart.defaults.global.defaultFontFamily = "Nunito";
	Chart.defaults.global.defaultFontColor = '#888';
	Chart.defaults.global.defaultFontSize = '14';

	var ctx = document.getElementById('chart').getContext('2d');

	var chart = new Chart(ctx, {
		type: 'line',

		// The data for our dataset
		data: {
			labels: ["January", "February", "March", "April", "May", "June"],
			// Information about the dataset
	   		datasets: [{
				label: "Views",
				backgroundColor: 'rgba(42,65,232,0.08)',
				borderColor: '#2a41e8',
				borderWidth: "3",
				data: [196,132,215,362,210,252],
				pointRadius: 5,
				pointHoverRadius:5,
				pointHitRadius: 10,
				pointBackgroundColor: "#fff",
				pointHoverBackgroundColor: "#fff",
				pointBorderWidth: "2",
			}]
		},

		// Configuration options
		options: {

		    layout: {
		      padding: 10,
		  	},

			legend: { display: false },
			title:  { display: false },

			scales: {
				yAxes: [{
					scaleLabel: {
						display: false
					},
					gridLines: {
						 borderDash: [6, 10],
						 color: "#d8d8d8",
						 lineWidth: 1,
	            	},
				}],
				xAxes: [{
					scaleLabel: { display: false },  
					gridLines:  { display: false },
				}],
			},

		    tooltips: {
		      backgroundColor: '#333',
		      titleFontSize: 13,
		      titleFontColor: '#fff',
		      bodyFontColor: '#fff',
		      bodyFontSize: 13,
		      displayColors: false,
		      xPadding: 10,
		      yPadding: 10,
		      intersect: false
		    }
		},


});

</script>

<script type="text/javascript">
    $(".form_datetime").datetimepicker({format: 'yyyy-mm-dd'});
</script> 

<!-- Google Autocomplete -->
<script>
	function initAutocomplete() {
		 var options = {
		  types: ['(cities)'],
		  // componentRestrictions: {country: "us"}
		 };

		 var input = document.getElementById('autocomplete-input');
		 var autocomplete = new google.maps.places.Autocomplete(input, options);

		if ($('.submit-field')[0]) {
		    setTimeout(function(){ 
		        $(".pac-container").prependTo("#autocomplete-container");
		    }, 300);
		}
	}
</script>

<!-- Google API & Maps -->
<!-- Geting an API Key: https://developers.google.com/maps/documentation/javascript/get-api-key -->
<script src="https://maps.googleapis.com/maps/api/js?key=&libraries=places"></script>


</body>
</html>

anuncios/templates/anuncios/empresa_lista_anuncio.html
{% extends 'anuncios/base_anuncio.html' %}
{% load staticfiles %}


{% block content %}


	<!-- Dashboard Content
	================================================== -->
	<div class="dashboard-content-container" data-simplebar>
		<div class="dashboard-content-inner" >
			
			<!-- Dashboard Headline -->
			<div class="dashboard-headline">
				<h3>Administración de Empleos</h3>

				<!-- Breadcrumbs -->
				<nav id="breadcrumbs" class="dark">
					<ul>
						<li><a href="#">Inicio</a></li>
						<li><a href="#">Panel</a></li>
						<li>Administracion de Empleis</li>
					</ul>
				</nav>
			</div>
	
			<!-- Row -->
			<div class="row">

				<!-- Dashboard Box -->
				<div class="col-xl-12">
					<div class="dashboard-box margin-top-0">

						<!-- Headline -->
						<div class="headline">
							<h3><i class="icon-material-outline-business-center"></i> Mis Empleos</h3>
						</div>

						<div class="content">
							
							{% if object_list %}
							{% for anuncio in object_list %}
							<ul class="dashboard-box-list">
								<li>
									<!-- Job Listing -->
									<div class="job-listing">

										<!-- Job Listing Details -->
										<div class="job-listing-details">

											<!-- Details -->
											<div class="job-listing-description">
												<h3 class="job-listing-title"><a href="#">{{ anuncio.titulo_anuncio }}</a> <span class="dashboard-status-button green">Pending Approval</span></h3>

												<!-- Job Listing Footer -->
												<div class="job-listing-footer">
													<ul>
														<li><i class="icon-material-outline-date-range"></i> {{ anuncio.fecha_anuncio }}</li>
														<li><i class="icon-material-outline-date-range"></i> {{ anuncio.fecha_cierre_anuncio }}</li>
													</ul>
												</div>
											</div>
										</div>
									</div>

									<!-- Buttons -->
									<div class="buttons-to-right always-visible">
										<a href="{% url 'anuncios:anuncio_editar' anuncio.id_anuncio %}" class="button gray ripple-effect ico" title="Editar" data-tippy-placement="top"><i class="icon-feather-edit"></i></a>
										<a href="{% url 'anuncios:anuncio_eliminar' anuncio.id_anuncio %}" class="button gray ripple-effect ico" title="Eliminar" data-tippy-placement="top"><i class="icon-feather-trash-2"></i></a>
									</div>
								</li>
							</ul>
							{% endfor %}
							
							{% else %}
							<h1> No hay Anuncios aún</h1>
							{% endif %}
						</div>
					</div>
				</div>

			</div>
			<!-- Row / End -->

			<!-- Footer -->
			<div class="dashboard-footer-spacer"></div>
			<div class="small-footer margin-top-15">
				<div class="small-footer-copyrights">
					2018 <strong>Bolsa de empleo</strong>
				</div>
				<div class="clearfix"></div>
			</div>
			<!-- Footer / End -->

		</div>
	</div>
	<!-- Dashboard Content / End -->

{% endblock %}

anuncios/templates/anuncios/postulante_lista_anuncio.html
{% extends 'anuncios/base_anuncio_postulante.html' %}
{% load staticfiles %}


{% block content %}

	<!-- Dashboard Content
	================================================== -->
	<div class="dashboard-content-container" data-simplebar>
		<div class="dashboard-content-inner" >
			
			<!-- Dashboard Headline -->
			<div class="dashboard-headline">
				<h3>Administración de Empleos</h3>

				<!-- Breadcrumbs -->
				<nav id="breadcrumbs" class="dark">
					<ul>
						<li><a href="#">Inicio</a></li>
						<li><a href="#">Panel</a></li>
						<li>Administracion de Empleos</li>
					</ul>
				</nav>
			</div>
	
			<!-- Row -->
			<div class="row">

				<!-- Dashboard Box -->
				<div class="col-xl-12">
					<div class="dashboard-box margin-top-0">

						<!-- Headline -->
						<div class="headline">
							<h3><i class="icon-material-outline-business-center"></i> Mis Empleos</h3>
						</div>

						<div class="content">
					<!-- Jobs Container -->
				<div class="listings-container compact-list-layout margin-top-35">
							{% if object_list %}
							{% for anuncio in object_list %}
							
							<!-- Job Listing -->
					<a href="{% url 'anuncios:display_anuncio' anuncio.id_anuncio %}" class="job-listing with-apply-button">

						<!-- Job Listing Details -->
						<div class="job-listing-details">

							<!-- Logo -->
							<div class="job-listing-company-logo">
								<img src="images/company-logo-01.png" alt="">
							</div>

							<!-- Details -->
							<div class="job-listing-description">
								<h3 class="job-listing-title">{{ anuncio.titulo_anuncio }}</h3>

								<!-- Job Listing Footer -->
								<div class="job-listing-footer">
									<ul>
										<li><i class="icon-material-outline-business"></i> {{ anuncio.user_ptr_id }} <div class="verified-badge" title="Verified Employer" data-tippy-placement="top"></div></li>
										<li><i class="icon-material-outline-location-on"></i> Santiago</li>
										<li><i class="icon-material-outline-business-center"></i>{{ anuncio.tipo_trabajo }}</li>
										<li><i class="icon-material-outline-access-time"></i> 3 días atras</li>
									</ul>
								</div>
							</div>

							<!-- Apply Button -->
							<span class="list-apply-button ripple-effect">Postular</span>
						</div>
					</a>	
							{% endfor %}
							
							{% else %}
							<h1> No hay Anuncios aún</h1>
							{% endif %}
							</div>
						</div>
					</div>
				</div>

			</div>
			<!-- Row / End -->


{% endblock %}